import os

#数据库配置
HOSTNAME = "127.0.0.1"
PORT     = "3306"
DATABASE = "abc"
USERNAME = "root"
PASSWORD = "245442"
DB_URI = "mysql+pymysql://{}:{}@{}:{}/{}?charset=utf8".format(USERNAME,PASSWORD,HOSTNAME,PORT,DATABASE)

SQLALCHEMY_DATABASE_URI= DB_URI
SQLALCHEMY_TRACK_MODIFICATIONS= True

SECRET_KEY = "2525252"